// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOq4Std83TjRAR84aFqFG7fSIYrrtyV3w',
    appId: '1:315393699829:web:819573724051af67d07abc',
    messagingSenderId: '315393699829',
    projectId: 'smartnote-22bc5',
    authDomain: 'smartnote-22bc5.firebaseapp.com',
    storageBucket: 'smartnote-22bc5.firebasestorage.app',
    measurementId: 'G-QV60X1B9S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAClj-zbCwntpXewMBqUDUEhfOp2EQKbKA',
    appId: '1:315393699829:android:a09c579791559a2ed07abc',
    messagingSenderId: '315393699829',
    projectId: 'smartnote-22bc5',
    storageBucket: 'smartnote-22bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEb_AK9CdBzVFuCIT2Xgaywx5_jms8aM',
    appId: '1:315393699829:ios:d5b7e741b50bcd50d07abc',
    messagingSenderId: '315393699829',
    projectId: 'smartnote-22bc5',
    storageBucket: 'smartnote-22bc5.firebasestorage.app',
    iosBundleId: 'com.example.smartnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEb_AK9CdBzVFuCIT2Xgaywx5_jms8aM',
    appId: '1:315393699829:ios:d5b7e741b50bcd50d07abc',
    messagingSenderId: '315393699829',
    projectId: 'smartnote-22bc5',
    storageBucket: 'smartnote-22bc5.firebasestorage.app',
    iosBundleId: 'com.example.smartnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOq4Std83TjRAR84aFqFG7fSIYrrtyV3w',
    appId: '1:315393699829:web:341002948fb78b35d07abc',
    messagingSenderId: '315393699829',
    projectId: 'smartnote-22bc5',
    authDomain: 'smartnote-22bc5.firebaseapp.com',
    storageBucket: 'smartnote-22bc5.firebasestorage.app',
    measurementId: 'G-15BY7PKGVZ',
  );
}